version: '3.4'
services:
  udpclient:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - udpserver
    environment:
      UDP_SERVER_HOSTNAME: "udpserver"
      UDP_SERVER_PORT: "8002"
      APP_MODE: "2"
  udpserver:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8002:8002
    environment:
      UDP_SERVER_PORT: "8002"
      APP_MODE: "3"

